### ISSUE TITLE
rri-100-1 root file uploaded

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#21]
New root file created for the RRI skills track:

- Title: Understanding Responsibility
- Module: What is Responsible Research and Innovation?
- Section: 1

## Tasks

- [ ] Create script
- [ ] Create slides for OLE
- [ ] Create slides for workshop
- [ ] Create guidebook section

**Comment by chrisdburr** [comment]
Hey, what did you mean by this:

https://github.com/alan-turing-institute/turing-commons/blob/90ee76a579ee6003bd6d8faf47fc75c48edabe8b/drafts/rri-skillstrack/rri-modules/RRI-100-1.md?plain=1#L40

**Comment by ClauFischer** [comment]
Review of root file:
- [ ] The good versus bad in this line is a bit confusing, because it's unclear whether it is talking about good versus bad opportunities or good v bad consequences.

https://github.com/alan-turing-institute/turing-commons/blob/32e4553cae9307ef552b42299692a6104a4cf171/drafts/rri-skillstrack/rri-modules/root-files/rri-100-1.md?plain=1#L64

- [ ] I would suggest to move this section up in the document, between the introduction and the section titled "two questions about responsibility in science and technology"
The reason for this is that I think the clarification on the difference between responsibility and accountability is super useful, and would make the examples of the Manhattan project and harmless torturer even clearer. And then this flows directly from examples into kinds of responsibility.
https://github.com/alan-turing-institute/turing-commons/blob/32e4553cae9307ef552b42299692a6104a4cf171/drafts/rri-skillstrack/rri-modules/root-files/rri-100-1.md?plain=1#L126

- [ ] Instead of saying "in addition" to the above types, maybe it should say something like; with respect to moral and legal responsibility, it is worth drawing further distinctions...
As it is phrased now, it sounds like these two topics are completely new instead of just having been talked about in the last section.
https://github.com/alan-turing-institute/turing-commons/blob/ba6c55e8511264d66c65a1dbd47857745ece75ab/drafts/rri-skillstrack/rri-modules/root-files/rri-100-1.md?plain=1#L156

- [ ] Add reference to supererogatory duties.
https://github.com/alan-turing-institute/turing-commons/blob/ba6c55e8511264d66c65a1dbd47857745ece75ab/drafts/rri-skillstrack/rri-modules/root-files/rri-100-1.md?plain=1#L169

**Comment by chrisdburr** [comment]
>     * [ ]  The good versus bad in this line is a bit confusing, because it's unclear whether it is talking about good versus bad opportunities or good v bad consequences.

Deleted brackets.

>     * [ ]  I would suggest to move this section up in the document, between the introduction and the section titled "two questions about responsibility in science and technology"
>       The reason for this is that I think the clarification on the difference between responsibility and accountability is super useful, and would make the examples of the Manhattan project and harmless torturer even clearer. And then this flows directly from examples into kinds of responsibility.

Done. 

>     * [ ]  Instead of saying "in addition" to the above types, maybe it should say something like; with respect to moral and legal responsibility, it is worth drawing further distinctions...
>       As it is phrased now, it sounds like these two topics are completely new instead of just having been talked about in the last section.

Adopted your suggestion. 

>     * [ ]  Is there a reason why we are focusing specifically on data controllers and processors? Seems overly specific when compared to the rest of the section.

Nope. Not sure why this was here. Removed the unnecessary sentence.

>     * [ ]  Add reference to supererogatory duties.
>       https://github.com/alan-turing-institute/turing-commons/blob/ba6c55e8511264d66c65a1dbd47857745ece75ab/drafts/rri-skillstrack/rri-modules/root-files/rri-100-1.md?plain=1#L169

Yes. Please do.

>     * [ ]  I am a bit confused as to the relevance go Human Rights  Law to the fact that the law usually setting the threshold for acceptable behaviour yet remaining silent on what constitutes praiseworthy behaviour.

It's probably easiest to just remove this, rather than expanding on the point on the web version. It's mostly a tangential point that's specific to Human Rights Law that I am not explaining well enough.

**Comment by ClauFischer** [comment]
**On Task 3: Draft web version**
- [ ] Is there a way I can preview the draft?

**Comment by ClauFischer** [comment]
@chrisdburr 
https://github.com/alan-turing-institute/turing-commons/blob/89a20b4f0f2fc876c121778f38cd76ef26667561/drafts/rri-skillstrack/rri-modules/root-files/rri-100-1.md?plain=1#L186

For this source I am assuming it is [this paper](https://link.springer.com/referenceworkentry/10.1007/978-3-030-03227-2_6-1) by David Heyd. Please let me know if I'm mistaken so I can change it.

**Comment by chrisdburr** [comment]
Firstly, well done on working around the typo. It is a David Heyd reference, but it's actually his book: https://philarchive.org/rec/HEYSIS

**Comment by ClauFischer** [comment]
@chrisdburr The book is from 1982 though, is this the right one? Or are you quoting a newer version?

**Comment by chrisdburr** [comment]
It's entirely possible I was using the reference to his SEP article: https://plato.stanford.edu/entries/supererogation/

To be honest, it's not too important. There are lots of references that could be used here, as it's just a source for the term 'supererogatory', which is used a lot in the moral philosophy literature.

Let's go with the SEP article. It's the most accessible.
