### ISSUE TITLE
rri-100-2 (collective responsibility)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#22]
The following root file has been created:

- Title: Collective Responsibility
- Module: What is Responsible Research and Innovation
- Skills Track: Responsible Research and Innovation
- Section: 2

## Tasks

- [ ] Review root file
- [ ] Draft web version
- [ ] Review web version 
- [ ] Create slides
- [ ] Review slides and draft script

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-100-2.md

**Comment by chrisdburr** [comment]
I’m not that happy with the arguments for collective responsibility section. Do you think you could try to improve this section by adding a stronger argument against collective responsibility?

https://github.com/alan-turing-institute/turing-commons/blob/8c007705725957aa65e2ff03d749fc2fdb69b552/drafts/rri-skillstrack/rri-modules/root-files/rri-100-2.md?plain=1#L71-L88

**Comment by ClauFischer** [comment]
- [ ] I think there is an interesting wider issue around collective responsibility, although I'm unsure where exactly the place for it would be. I think problems with a structure similar to the tragedy of the commons are super widespread and some of the biggest problems we face as a species have this structure (anthropogenic climate change, safe AI development, etc). I know it's not exactly collective responsibility but it is related and I think it might be interesting to have something on it.
https://github.com/alan-turing-institute/turing-commons/blob/ba6c55e8511264d66c65a1dbd47857745ece75ab/drafts/rri-skillstrack/rri-modules/root-files/rri-100-2.md?plain=1#L36

- [ ] Add to section on arguments against collective responsibility.

**Comment by chrisdburr** [comment]
Imagine a situation where an individual transgress some norm, and the affect is that a team are all penalised (e.g. stricter measures are brought in). As a result, the team may end up holding each other responsible to avoid further punishment. 

Not suggesting this is an ethical behaviour mind you. Just noting that it happens.

**Comment by ClauFischer** [comment]
@chrisdburr I have drafted something for the "arguments against collective responsibility section".
However, when reading through the section again, I think there might be some confusion (perhaps only on my part!) as to the difference between collective and distributed responsibility. Maybe it's worth having a short discussion on it, to make sure I am adding useful content. Thanks :)

**Comment by ClauFischer** [comment]
@chrisdburr Yes, I'll tick that off.
