### ISSUE TITLE
rri-100-3 (defining responsible research and innovation)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#23]
The following root file has been created:

- Title: Defining Responsible Research and Innovation
- Module: What is Responsible Research and Innovation?
- Skills Track: Responsible Research and Innovation in Data Science and AI
- Section: 3

## Tasks

- [ ] Review root file
- [ ] Draft web version
- [ ] Review web version 
- [ ] Create slides
- [ ] Review slides and draft script

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-100-3.md

**Comment by ClauFischer** [comment]
- Hi Chris, there are no comments that need your revision in this root file :)

- [ ] Add example of YouTube recommendation algorithm as something which may have seem innocuous ex-ante, but has had huge impacts.

https://github.com/alan-turing-institute/turing-commons/blob/b63378453d917d48ad9b61ba82499eba1908f1f5/drafts/rri-skillstrack/rri-modules/root-files/rri-100-3.md?plain=1#L64
