### ISSUE TITLE
rri-100-4 (The Scope and Horizon of Responsibility)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#24]
The following root file has been created:

- Title: The Scope and Horizon of Responsibility
- Module: What is Responsible Research and Innovation?
- Skills Track: RRI in Data Science and AI
- Section: 4

## Tasks

- [ ] Review root file
- [ ] Draft web version
- [ ] Review web version 
- [ ] Create slides
- [ ] Review slides and draft script

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-100-4.md

**Comment by ClauFischer** [comment]
- [ ] Maybe add a couple of more explanatory phrases to the the responsibility of future generations sections

https://github.com/alan-turing-institute/turing-commons/blob/64a1b6b3b7fdc39a71a9c734ca8800f363137a7f/drafts/rri-skillstrack/rri-modules/root-files/rri-100-4.md?plain=1#L143

- [ ] Why would the possible section on existential risks fall under next steps? I would have put it as a subsection of responsibility to future generations. Will draft something for the web version.

https://github.com/alan-turing-institute/turing-commons/blob/64a1b6b3b7fdc39a71a9c734ca8800f363137a7f/drafts/rri-skillstrack/rri-modules/root-files/rri-100-4.md?plain=1#L185

**Comment by chrisdburr** [comment]
@ClauFischer just checking if you need further input here before I check the second task?

On the previous point about existential risks, please ignore it for the time being. It was just a possible option.

**Comment by ClauFischer** [comment]
@chrisdburr I have ticked it off
