### ISSUE TITLE
rri-101-1 (What is the Project Lifecycle?)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#25]
The following root file has been created:

- Title: What is the Project Lifecycle?
- Module: The Project Lifecycle
- Skills Track: RRI in Data Science and AI
- Section: 1

## Tasks

- [ ] Review root file
- [ ] Draft web version
- [ ] Review web version 
- [ ] Create slides
- [ ] Review slides and draft script

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-101-1.md
