### ISSUE TITLE
rri-101-2 (Project Design)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#26]
The following root file has been created:

- Title: Project Design
- Module: The Project Lifecycle
- Skills Track: RRI
- Section: 2

## Tasks

- [ ] Review root file
- [ ] Draft web version
- [ ] Review web version 
- [ ] Create slides
- [ ] Review slides and draft script

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-101-2.md

**Comment by ClauFischer** [comment]
- [ ]
https://github.com/alan-turing-institute/turing-commons/blob/9a22c5fdca9e0f507aec86ee97cec1256a037df7/drafts/rri-skillstrack/rri-modules/root-files/rri-101-2.md?plain=1#L29
