### ISSUE TITLE
rri-101-3 (model development)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#27]
The following root file has been created:

- Title: Model Development
- Module: The Project Lifecycle
- Skills Track: RRI
- Section: 3

## Tasks

- [ ] Review root file (Clau)
- [ ] Answer comments (Chris)
- [ ] Draft web version (Clau)
- [ ] Review web version (Chris)
- [ ] Create slides (Chris)
- [ ] Review slides and draft script (Clau)

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-101-3.md

**Comment by ClauFischer** [comment]
- No comments for you to answer Chris :)

- [ ] Do this:

https://github.com/alan-turing-institute/turing-commons/blob/885bc236669a03ac145419efb5a86a76abc75ba0/drafts/rri-skillstrack/rri-modules/root-files/rri-101-3.md?plain=1#L29
