### ISSUE TITLE
rri-101-4 (system deployment)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#28]
The following root file has been created:

- Title: System Deployment
- Module: The Project Lifecycle
- Skills Track: RRI
- Section: 4

## Tasks

- [ ] Review root file (Clau)
- [ ] Answer comments (Chris)
- [ ] Draft web version (Clau)
- [ ] Review web version (Chris)
- [ ] Create slides (Chris)
- [ ] Review slides and draft script (Clau)

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-101-4.md

**Comment by ClauFischer** [comment]
- No comments for you to answer Chris :)

- [ ] Do this:

https://github.com/alan-turing-institute/turing-commons/blob/740cf26def2a4baff9e8076dc98e51652b123259/drafts/rri-skillstrack/rri-modules/root-files/rri-101-4.md?plain=1#L29

- [ ] Insert this when available

https://github.com/alan-turing-institute/turing-commons/blob/740cf26def2a4baff9e8076dc98e51652b123259/drafts/rri-skillstrack/rri-modules/root-files/rri-101-4.md?plain=1#L171

- [ ] Add further resources
https://github.com/alan-turing-institute/turing-commons/blob/740cf26def2a4baff9e8076dc98e51652b123259/drafts/rri-skillstrack/rri-modules/root-files/rri-101-4.md?plain=1#L184

**Comment by ClauFischer** [comment]
@chrisdburr Is this paper (https://doi.org/10.1002/bdm.2155) the cited burton2019 in this line?
https://github.com/alan-turing-institute/turing-commons/blob/5e1719d52ce57dd146bcc1008e169f94541e2f06/drafts/rri-skillstrack/rri-modules/root-files/rri-101-4.md?plain=1#L82

**Comment by chrisdburr** [comment]
It's this collection: https://www.oxfordbibliographies.com/display/document/obo-9780199828340/obo-9780199828340-0159.xml
