### ISSUE TITLE
rri-204-1 [what is explainability]

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#35]
The following root file has been created:

- Title: What is explainability?
- Module: rri-204 (Explainability, SAFE-D)
- Skills Track: Responsible Research and Innovation
- Section: 1

## Tasks

- [x] Review root file (Clau)
- [x] Answer comments (Chris)
- [x] Draft web version (Clau)
- [ ] Review web version (Chris)
- [x] Create slides (Chris)
- [ ] Review slides and draft script (Clau)

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-204-1.md

**Comment by ClauFischer** [comment]
- [ ] I found it a bit confusing to start the defining explainability with a definition of interpretability and never having one general definition of explainability.
https://github.com/alan-turing-institute/turing-commons/blob/ae9be6c2d85f0c27a1f5b1a0d91fb448c339c182/drafts/rri-skillstrack/rri-modules/root-files/rri-204-1.md?plain=1#L88

- [ ] I also found this section a bit too abstract, perhaps an example might help clarify the point.
https://github.com/alan-turing-institute/turing-commons/blob/ae9be6c2d85f0c27a1f5b1a0d91fb448c339c182/drafts/rri-skillstrack/rri-modules/root-files/rri-204-1.md?plain=1#L179

**Comment by chrisdburr** [comment]
I've updated the draft to reflect these comments:

1) I've left the ordering of interpretability --> explainability as is, but made the structure clearer.
2) I've removed the (optional) admonition on pragmatic vs. epistemic considerations.

**Comment by ClauFischer** [comment]
@chrisdburr Is this (https://arxiv.org/pdf/1706.07269.pdf) the Miller, 2017 cited quoted here:
https://github.com/alan-turing-institute/turing-commons/blob/9b25138ba268edd3393ab386553b34d19abd93cc/drafts/rri-skillstrack/rri-modules/root-files/rri-204-1.md?plain=1#L93

**Comment by chrisdburr** [comment]
Yes, but that's the preprint. Here is the published version: https://www.sciencedirect.com/science/article/pii/S0004370218305988
