### ISSUE TITLE
rri-204-2 [project transparency]

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#37]
The following root file has been created:

- Title: Project Transparency
- Module: Explainability (SAFE-D Module)
- Skills Track: RRI
- Section: 2

## Tasks

- [ ] Review root file (Clau)
- [ ] Answer comments (Chris)
- [ ] Draft web version (Clau)
- [ ] Review web version (Chris)
- [ ] Create slides (Chris)
- [ ] Review slides and draft script (Clau)

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md

**Comment by ClauFischer** [comment]
- [ ] @chrisdburr I think this sentence may be a bit confusing. It suggests that what has changed is people's purchasing behaviour (which may have happened), but what we have been exploring is the change in recommendations by the site's recommendation algorithm. We haven't yet established that this recommendations have then changed people's actual purchasing patterns. Unless I am missing something, I would suggest changing to something like "... that explains the change in the distribution of the system's recommendations".

https://github.com/alan-turing-institute/turing-commons/blob/45bc1bec19fdff98c05ccc06b6138329d23d176d/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L48

- [ ] @chrisdburr Again this seems to be another case where we are not keeping a clear enough distinction between the model's behaviour and the customers' final purchasing behaviours (which are of course correlated). I would suggest changing the sentence below to something like "Here, it is the customers' actual behaviour which has changed drastically (they are now purchasing less holiday packs). However, it is sensible for the data analysts to assume that there has been another underlying shift in the data distribution (similar to the seasonal shift above), which has changed the model's behaviour in a way that affects customer's final behaviour."

https://github.com/alan-turing-institute/turing-commons/blob/45bc1bec19fdff98c05ccc06b6138329d23d176d/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L52
- [ ] @chrisdburr I have added an explanatory sentence after this:
https://github.com/alan-turing-institute/turing-commons/blob/45bc1bec19fdff98c05ccc06b6138329d23d176d/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L59

- [ ] @chrisdburr I think something may be missing to this phrase:
https://github.com/alan-turing-institute/turing-commons/blob/45bc1bec19fdff98c05ccc06b6138329d23d176d/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L106

**Comment by chrisdburr** [comment]
@ClauFischer, please take a look at this revised section when you have a chance:

https://github.com/alan-turing-institute/turing-commons/blob/2a4f039d34d64628cb7506523572f3585afd239c/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L48-L67

**Comment by ClauFischer** [comment]
@chrisdburr:
- [ ] Here it says recommending when it should only be predicting at this stage.
https://github.com/alan-turing-institute/turing-commons/blob/a9e0b01479067bdb2e0f3d18e6551accd657f289/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L50

- [ ] I think that if we are changing to a recommender system now we should say something about it being a different model (that it's now a recommender system and not only a predictive system).
https://github.com/alan-turing-institute/turing-commons/blob/a9e0b01479067bdb2e0f3d18e6551accd657f289/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L58

- [ ] Perhaps a footnote should be added to say that there may be fault in the fact that the model is discriminating based on locations, even though there is no error in the way the model is operating (it's the data pipeline). Although, on the other  hand, you have already mentioned that the practice is ethically-dubious.
https://github.com/alan-turing-institute/turing-commons/blob/a9e0b01479067bdb2e0f3d18e6551accd657f289/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L65


Let me know what you think about these suggestions and I can draft some amendments and send them for your revision 😃

**Comment by chrisdburr** [comment]
I think I've answered all your comments. Main changes are as follows:

https://github.com/alan-turing-institute/turing-commons/blob/bd0125fa1f2da9e880f96427a4b085fe2fa99ff2/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L113

https://github.com/alan-turing-institute/turing-commons/blob/d27af9cfe93edb386309bde2f771020b2f8aa117/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L48-L68

**Comment by ClauFischer** [comment]
@chrisdburr Is this paper (https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=36708ab24406aa3ec931fb9ba3f4a6cd7c3bd4b6) the one you want to refer to in this line
https://github.com/alan-turing-institute/turing-commons/blob/ce85f445030fb9d36578b502a166bd7c26030614/drafts/rri-skillstrack/rri-modules/root-files/rri-204-2.md?plain=1#L164
?

Right now, both links take you to the Washington Post article. I searched through our conversations and the paper I just posted was the one I sent as more academic. If it is not, let me know please so I can link to the correct paper.
