### ISSUE TITLE
rri-204-4 (situated explanations)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#38]
The following root file has been created:

- Title: Situated Explanations
- Module: Explainability (SAFE-D Principle)
- Skills Track: RRI
- Section: 4

## Tasks

- [ ] Review root file (Clau)
- [ ] Answer comments (Chris)
- [ ] Draft web version (Clau)
- [ ] Review web version (Chris)
- [ ] Create slides (Chris)
- [ ] Review slides and draft script (Clau)

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/rri-modules/root-files/rri-204-4.md

**Comment by chrisdburr** [comment]
@ClauFischer: I'm cretaing this issue before the root file is 100% complete. There are a couple of reasons for this:

1. There is a possible section on social trust and explainability, which I was wondering if you'd be interested in authoring based on the PED chapter you wrote. 
2. I'd appreciate general feedback about the overall scope of the section before I decide what else needs to be added or revised. I don't believe the section is that focused at the moment.

**Comment by ClauFischer** [comment]
-  [ ] Look up resources for ethics of generative AI:
https://github.com/alan-turing-institute/turing-commons/blob/673de90f4aff4b8c0d3fd28ba380d26cb2587d07/drafts/rri-skillstrack/rri-modules/root-files/rri-204-4.md?plain=1#L40

- [ ] Insert explanatory graphic on attention mechanisms for LLMs:
https://github.com/alan-turing-institute/turing-commons/blob/673de90f4aff4b8c0d3fd28ba380d26cb2587d07/drafts/rri-skillstrack/rri-modules/root-files/rri-204-4.md?plain=1#L73

- [ ] I'm not sure if this section is the clearest but perhaps it's just the nature of the topic:
https://github.com/alan-turing-institute/turing-commons/blob/673de90f4aff4b8c0d3fd28ba380d26cb2587d07/drafts/rri-skillstrack/rri-modules/root-files/rri-204-4.md?plain=1#L62

- [  ] I'm not sure I understand the relevance of the situated cognition admonition.
https://github.com/alan-turing-institute/turing-commons/blob/82de42b600ae7951651688eccb064cf44ac47882/drafts/rri-skillstrack/rri-modules/root-files/rri-204-4.md?plain=1#L181

- [ ] Add section
https://github.com/alan-turing-institute/turing-commons/blob/82de42b600ae7951651688eccb064cf44ac47882/drafts/rri-skillstrack/rri-modules/root-files/rri-204-4.md?plain=1#L199

**Comment by chrisdburr** [comment]
The situated cognition section is an optional one. If you think it is distracting, feel free to remove it. 

Let's talk about the explanatory graphic for LLM. It's not a trivial task.
