### ISSUE TITLE
rri-203-3 (statistical fairness)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#44]
The following root file has been created:

- Title: Statistical Fairness
- Module: Fairness
- Skills Track: RRI
- Section: 3

## Tasks

- [ ] Review root file (Clau)
- [ ] Answer comments (Chris)
- [ ] Draft web version (Clau)
- [ ] Review web version (Chris)
- [ ] Create slides (Chris)
- [ ] Review slides and draft script (Clau)

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/root-files/rri-203-3.md

**Comment by ClauFischer** [comment]
**NO CHRIS INPUT NEEDED**
- [ ] double check precision and recall def
- [ ] when male and female example is introduced, females have high levels of FP. Does this mean that the model will fail to identify a large number of female patients who need to be sent for further testing
[ ] Add barocas et al reference
[ ] Important to add that three crtieria for fairness are incompatible between them
