### ISSUE TITLE
rri-203-a1 (Bias Reflectlist)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/turing-commons#46]
The following root file has been created:

- Title: Bias Reflectlist 
- Module: Fairness
- Skills Track: Responsible Research and Innovation
- Section: Activity 1

## Tasks

- [ ] Review root file
- [ ] Send to Nerea 
- [ ] Review draft document
- [ ] Approve activity handout

Link to file: https://github.com/alan-turing-institute/turing-commons/blob/drafts/drafts/rri-skillstrack/activities/rri-203-a1.md
